#!/usr/bin/env python3
"""Pelican entrypoint. Operator values are data, never shell source."""
import argparse
import base64
import hashlib
import json
import os
from pathlib import Path
import re
import signal
import shutil
import subprocess
import sys
import tempfile
import time


def private_write(path, text):
    if path.is_symlink():
        raise ValueError(f'Refusing a symlink at managed file {path.name}')
    with tempfile.NamedTemporaryFile(mode='w', dir=path.parent, delete=False) as handle:
        temporary = Path(handle.name)
        try:
            os.chmod(temporary, 0o600)
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        except BaseException:
            temporary.unlink(missing_ok=True)
            raise
    try:
        temporary.replace(path)
    finally:
        temporary.unlink(missing_ok=True)


def resource_snapshot(root):
    result = {}
    for path in root.rglob('*'):
        if path.is_symlink():
            raise ValueError('Resource symlinks are not supported')
        if path.is_file():
            result[str(path.relative_to(root))] = hashlib.sha256(path.read_bytes()).hexdigest()
    return result


def seed(data, app):
    for name in ['config', 'server-data', 'txData', 'recovery']:
        target = data / name
        if target.is_symlink():
            raise ValueError(f'Refusing a symlink at state directory {name}')
        target.mkdir(parents=True, exist_ok=True)
    resources = data / 'server-data/resources'
    expected = app / 'resources'
    if resources.is_symlink():
        raise ValueError('Resource symlinks are not supported; preserve state and reinstall resources')
    if resources.exists():
        if not resources.is_dir() or resource_snapshot(resources) != resource_snapshot(expected):
            raise ValueError('Resources differ from this image; stop, back up and move the old resources directory before reinstalling')
    else:
        shutil.copytree(expected, resources)
    operator = data / 'config/operator.cfg'
    if not operator.exists() and not operator.is_symlink():
        private_write(operator, '# Private operator settings. Authorize each tester using their own server-verified identifier:\n'
                      '# add_ace identifier.license:YOUR_TESTER_IDENTIFIER ofm.join allow\n')


def integer(env, name, default, low, high):
    value = env.get(name, str(default))
    if not re.fullmatch(r'[0-9]+', value):
        raise ValueError(f'{name} must be an integer')
    parsed = int(value)
    if not low <= parsed <= high:
        raise ValueError(f'{name} is out of range')
    return parsed


def quoted(value):
    if any(ord(char) < 32 or ord(char) == 127 for char in value):
        raise ValueError('Configuration text cannot contain control characters')
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def configure(data, env):
    key = env.get('FIVEM_LICENSE_KEY', '')
    if not re.fullmatch(r'[A-Za-z0-9_-]{8,128}', key):
        raise ValueError('FIVEM_LICENSE_KEY is missing or malformed')
    name = env.get('SERVER_NAME', 'Open Freemode Development')
    if not 1 <= len(name) <= 128:
        raise ValueError('SERVER_NAME must contain 1 to 128 characters')
    game_env = dict(env)
    if 'SERVER_PORT' in env:
        game_env['GAME_PORT'] = env['SERVER_PORT']
    game_port = integer(game_env, 'GAME_PORT', 30120, 1024, 65535)
    slots = integer(env, 'MAX_PLAYERS', 30, 1, 48)
    options = {}
    for setting, field in [('DB_HOST', 'host'), ('DB_NAME', 'database'), ('DB_USER', 'user'), ('DB_PASSWORD', 'password')]:
        value = env.get(setting, '')
        if not value or '\0' in value:
            raise ValueError(f'{setting} is missing or invalid')
        options[field] = value
    options['port'] = integer(env, 'DB_PORT', 3306, 1, 65535)
    lines = [
        '# Generated by Open Freemode. Edit Pelican settings and config/operator.cfg instead.',
        'exec ' + quoted(str(data / 'config/operator.cfg')),
        'sv_hostname ' + quoted(name),
        'sv_licenseKey ' + quoted(key),
        f'endpoint_add_tcp "0.0.0.0:{game_port}"',
        f'endpoint_add_udp "0.0.0.0:{game_port}"',
        f'sv_maxclients {slots}',
        'set onesync on',
        'sv_master1 ""',
        'sv_scriptHookAllowed 0',
        'set sv_devMode false',
        'add_convar_permission ofm_db read ofm_db_options',
        'set ofm_db_options ' + base64.b64encode(json.dumps(options, ensure_ascii=True).encode()).decode(),
        'ensure chat',
        'ensure ofm_db',
        'ensure ofm_core',
    ]
    private_write(data / 'config/database.json', json.dumps(options, ensure_ascii=True) + '\n')
    private_write(data / 'server-data/server.cfg', '\n'.join(lines) + '\n')
    child_env = {key: value for key, value in env.items()
                 if not key.startswith(('DB_', 'TXHOST_')) and key != 'FIVEM_LICENSE_KEY'}
    return child_env


def command(app):
    alpine = app / 'runtime/alpine'
    loader = alpine / 'lib/ld-musl-x86_64.so.1'
    server = alpine / 'opt/cfx-server/cfx-server'
    if not loader.is_file() or not server.is_file():
        raise ValueError('Pinned Enhanced runtime is missing; rebuild the image')
    # Enhanced still requires this argument from its official run.sh, even though
    # the artifact no longer contains a physical citizen directory.
    return [str(loader), '--library-path', f'{alpine}/lib:{alpine}/usr/lib', '--', str(server),
            '+set', 'citizen_dir', str(server.parent / 'citizen') + '/']


def supervise(arguments, env, cwd, grace=5):
    process = subprocess.Popen(arguments, env=env, cwd=cwd, start_new_session=True)
    stopped_at = None

    def send(sig):
        try:
            os.killpg(process.pid, sig)
        except ProcessLookupError:
            pass

    def stop(_signum, _frame):
        nonlocal stopped_at
        if stopped_at is None:
            stopped_at = time.monotonic()
            send(signal.SIGTERM)

    previous = {sig: signal.signal(sig, stop) for sig in (signal.SIGTERM, signal.SIGINT)}
    try:
        while process.poll() is None:
            if stopped_at is not None and time.monotonic() - stopped_at >= grace:
                send(signal.SIGKILL)
            time.sleep(0.05)
        # Cfx can return zero after a fatal license error. Any unsolicited exit
        # ends this persistent service and must be visible to Pelican as a failure.
        return 0 if stopped_at is not None else (process.returncode or 1) if process.returncode >= 0 else 128 - process.returncode
    finally:
        # A monitor can exit before its children; all of that process group belongs to this launch.
        send(signal.SIGKILL)
        process.wait()
        for sig, handler in previous.items():
            signal.signal(sig, handler)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('mode', choices=['install', 'configure', 'start', 'migrate'], nargs='?', default=os.environ.get('OFM_MODE', 'start'))
    parser.add_argument('--data-dir', type=Path, default=Path('/home/container'))
    parser.add_argument('--app-dir', type=Path, default=Path('/opt/open-freemode'))
    args = parser.parse_args()
    data, app = args.data_dir.absolute(), args.app_dir.absolute()
    try:
        if args.mode not in ['install', 'configure', 'start', 'migrate']:
            raise ValueError('OFM_MODE must be start or migrate')
        seed(data, app)
        if args.mode == 'install':
            print('Open Freemode persistent directories initialized; existing operator settings preserved.')
            return 0
        environment = configure(data, os.environ)
        if args.mode == 'configure':
            print('Private configuration generated.')
            return 0
        if args.mode == 'migrate':
            return subprocess.call(['node', str(app / 'scripts/migrate.mjs'), str(data / 'config/database.json')], env=environment)
        return supervise(command(app) + ['+exec', 'server.cfg'], environment, data / 'server-data')
    except (ValueError, OSError) as error:
        # OSError text may include private paths; only our fixed validation messages are shown.
        print(str(error) if isinstance(error, ValueError) else 'Launcher filesystem/process error; check private paths and permissions.', file=sys.stderr)
        return 1


if __name__ == '__main__':
    sys.exit(main())
