#!/usr/bin/env python3
"""Pelican entrypoint. Operator values are data, never shell source."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import select
import signal
import shutil
import subprocess
import sys
import tempfile
import threading
import time
from urllib.parse import quote


def private_write(path, text):
    if path.is_symlink():
        raise ValueError(f'Refusing a symlink at managed file {path.name}')
    with tempfile.NamedTemporaryFile(mode='w', dir=path.parent, delete=False) as handle:
        temporary = Path(handle.name)
        try:
            os.chmod(temporary, 0o600)
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        except BaseException:
            temporary.unlink(missing_ok=True)
            raise
    try:
        temporary.replace(path)
    finally:
        temporary.unlink(missing_ok=True)


def resource_snapshot(root):
    result = {}
    for path in root.rglob('*'):
        if path.is_symlink():
            raise ValueError('Resource symlinks are not supported')
        if path.is_file():
            result[str(path.relative_to(root))] = hashlib.sha256(path.read_bytes()).hexdigest()
    return result


def snapshot_digest(snapshot):
    encoded = json.dumps(snapshot, sort_keys=True, separators=(',', ':')).encode()
    return hashlib.sha256(encoded).hexdigest()


def seed(data, app):
    for name in ['config', 'server-data', 'txData', 'recovery']:
        target = data / name
        if target.is_symlink():
            raise ValueError(f'Refusing a symlink at state directory {name}')
        target.mkdir(parents=True, exist_ok=True)
    resources = data / 'server-data/resources'
    expected = app / 'resources'
    if resources.is_symlink():
        raise ValueError('Resource symlinks are not supported; preserve state and reinstall resources')
    if resources.exists():
        if not resources.is_dir():
            raise ValueError('Managed resources path is not a directory; preserve state and repair it before starting')
        current = resource_snapshot(resources)
        wanted = resource_snapshot(expected)
        if current != wanted:
            backup = data / 'recovery' / ('resources-' + snapshot_digest(current)[:16])
            staged = resources.with_name('.resources-' + snapshot_digest(wanted)[:16] + '.staged')
            if backup.exists() or staged.exists():
                raise ValueError('A preserved or staged resource bundle blocks this update; inspect recovery and retry')
            shutil.copytree(expected, staged)
            resources.rename(backup)
            try:
                staged.rename(resources)
            except BaseException:
                if not resources.exists():
                    backup.rename(resources)
                raise
            print(f'Installed updated resource bundle; previous files preserved as recovery/{backup.name}.', flush=True)
    else:
        shutil.copytree(expected, resources)
    operator = data / 'config/operator.cfg'
    if not operator.exists() and not operator.is_symlink():
        private_write(operator, '# Private operator settings. Authorize each tester using their own server-verified identifier:\n'
                      '# add_ace identifier.license:YOUR_TESTER_IDENTIFIER ofm.join allow\n')


def integer(env, name, default, low, high):
    value = env.get(name, str(default))
    if not re.fullmatch(r'[0-9]+', value):
        raise ValueError(f'{name} must be an integer')
    parsed = int(value)
    if not low <= parsed <= high:
        raise ValueError(f'{name} is out of range')
    return parsed


def quoted(value):
    if any(ord(char) < 32 or ord(char) == 127 for char in value):
        raise ValueError('Configuration text cannot contain control characters')
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def configure(data, env):
    key = env.get('FIVEM_LICENSE_KEY', '')
    if not re.fullmatch(r'[A-Za-z0-9_-]{8,128}', key):
        raise ValueError('FIVEM_LICENSE_KEY is missing or malformed')
    name = env.get('SERVER_NAME', 'Open Freemode Development')
    if not 1 <= len(name) <= 128:
        raise ValueError('SERVER_NAME must contain 1 to 128 characters')
    game_env = dict(env)
    if 'SERVER_PORT' in env:
        game_env['GAME_PORT'] = env['SERVER_PORT']
    game_port = integer(game_env, 'GAME_PORT', 30120, 1024, 65535)
    slots = integer(env, 'MAX_PLAYERS', 30, 1, 48)
    options = {}
    for setting, field in [('DB_HOST', 'host'), ('DB_NAME', 'database'), ('DB_USER', 'user'), ('DB_PASSWORD', 'password')]:
        value = env.get(setting, '')
        if not value or '\0' in value:
            raise ValueError(f'{setting} is missing or invalid')
        options[field] = value
    options['port'] = integer(env, 'DB_PORT', 3306, 1, 65535)
    lines = [
        '# Generated by Open Freemode. Edit Pelican settings and config/operator.cfg instead.',
        'exec ' + quoted(str(data / 'config/operator.cfg')),
        'sv_hostname ' + quoted(name),
        'sv_licenseKey ' + quoted(key),
        f'endpoint_add_tcp "0.0.0.0:{game_port}"',
        f'endpoint_add_udp "0.0.0.0:{game_port}"',
        f'sv_maxclients {slots}',
        'sv_master1 ""',
        'sv_scriptHookAllowed 0',
        'set sv_enforceGameBuild 3258',
        'set mysql_connection_string ' + quoted('mysql://' + quote(options['user'], safe='') + ':'
            + quote(options['password'], safe='') + '@' + options['host'] + ':' + str(options['port'])
            + '/' + quote(options['database'], safe='') + '?charset=utf8mb4'),
        'setr inventory:framework "qbx"',
        'setr inventory:weaponmismatch false',
        'setr qbx:enableBridge true',
        'set qbx:enableVehiclePersistence true',
        'set qbx:vehiclePersistenceType "semi"',
        'setr voice_useNativeAudio true',
        'setr voice_useSendingRangeOnly false',
        'setr voice_defaultCycle "F11"',
        'exec resources/ofm_session/freemode.cfg',
        'ensure chat',
        'ensure spawnmanager',
        'ensure sessionmanager',
        'ensure hardcap',
        'ensure baseevents',
        'ensure oxmysql',
        'ensure ox_lib',
        'ensure qbx_core',
        'ensure qbx_vehicles',
        'ensure ox_inventory',
        'ensure illenium-appearance',
        'ensure pma-voice',
        'ensure vMenu',
        'ensure ofm_activities',
        'ensure ofm_properties',
        'ensure ofm_vehicles',
        'ensure ofm_hub',
        'ensure ofm_session',
    ]
    private_write(data / 'config/database.json', json.dumps(options, ensure_ascii=True) + '\n')
    private_write(data / 'server-data/server.cfg', '\n'.join(lines) + '\n')
    child_env = {key: value for key, value in env.items()
                 if not key.startswith(('DB_', 'TXHOST_')) and key != 'FIVEM_LICENSE_KEY'}
    return child_env


def runtime_root(data, app, environment):
    checksum = json.loads((app / 'runtime.lock.json').read_text())['sha256']
    cache = data / 'runtime'
    target = cache / checksum
    if cache.is_symlink() or target.is_symlink():
        raise ValueError('Runtime cache must not be a symlink')
    cache.mkdir(exist_ok=True)
    if not target.exists():
        with tempfile.TemporaryDirectory(prefix='.download-', dir=cache) as temporary:
            staged = Path(temporary) / 'bundle'
            result = subprocess.run([sys.executable, str(app / 'scripts/fetch-runtime.py'),
                                     str(app / 'runtime.lock.json'), str(staged / 'runtime')],
                                    env=environment, capture_output=True)
            if result.returncode != 0:
                raise ValueError('Pinned runtime download failed; check Cfx connectivity and retry')
            command(staged)
            staged.rename(target)
        print('Pinned Legacy runtime downloaded and verified.', flush=True)
    return target


def command(app):
    alpine = app / 'runtime/alpine'
    loader = alpine / 'opt/cfx-server/ld-musl-x86_64.so.1'
    server = alpine / 'opt/cfx-server/FXServer'
    if not loader.is_file() or not server.is_file():
        raise ValueError('Pinned Legacy runtime cache is incomplete; preserve it and retry with a fresh cache')
    # Match the pinned Legacy artifact's run.sh, including its bundled V8 libraries.
    return [str(loader), '--library-path', f'{alpine}/usr/lib/v8:{alpine}/lib:{alpine}/usr/lib', '--', str(server),
            '+set', 'citizen_dir', str(server.parent / 'citizen') + '/']


def supervise(arguments, env, cwd, grace=5):
    # Keep Cfx on a real terminal, translating Wings' LF to terminal Enter (CR).
    # Its pipe-based console can hang while shutting down after a fatal error.
    bridge_console = os.isatty(0)
    master, slave = None, None
    if bridge_console:
        import pty
        import tty
        master, slave = pty.openpty()
        tty.setraw(slave)
    try:
        process = subprocess.Popen(arguments, env=env, cwd=cwd, start_new_session=True, stdin=slave)
    except BaseException:
        if master is not None:
            os.close(master)
        raise
    finally:
        if slave is not None:
            os.close(slave)
    stopped_at = None
    input_stopped = threading.Event()

    def console_input():
        previous_cr = False
        try:
            while not input_stopped.is_set():
                if not select.select([0], [], [], 0.1)[0]:
                    continue
                data = os.read(0, 4096)
                if not data:
                    break
                normalized = bytearray()
                for byte in data:
                    if byte != 10 or not previous_cr:
                        normalized.append(13 if byte == 10 else byte)
                    previous_cr = byte == 13
                offset = 0
                while offset < len(normalized):
                    offset += os.write(master, normalized[offset:])
        except (OSError, ValueError):
            pass  # Native exit/stop closes its terminal.

    input_thread = threading.Thread(target=console_input, daemon=True) if bridge_console else None
    if input_thread:
        input_thread.start()

    def send(sig):
        try:
            os.killpg(process.pid, sig)
        except ProcessLookupError:
            pass

    def stop(_signum, _frame):
        nonlocal stopped_at
        if stopped_at is None:
            stopped_at = time.monotonic()
            send(signal.SIGTERM)

    previous = {sig: signal.signal(sig, stop) for sig in (signal.SIGTERM, signal.SIGINT)}
    try:
        while process.poll() is None:
            if stopped_at is not None and time.monotonic() - stopped_at >= grace:
                send(signal.SIGKILL)
            time.sleep(0.05)
        # Cfx can return zero after a fatal license error. Any unsolicited exit
        # ends this persistent service and must be visible to Pelican as a failure.
        return 0 if stopped_at is not None else (process.returncode or 1) if process.returncode >= 0 else 128 - process.returncode
    finally:
        # A monitor can exit before its children; all of that process group belongs to this launch.
        send(signal.SIGKILL)
        process.wait()
        input_stopped.set()
        if input_thread:
            input_thread.join(timeout=1)
        if master is not None:
            os.close(master)
        for sig, handler in previous.items():
            signal.signal(sig, handler)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('mode', choices=['install', 'configure', 'start', 'migrate'], nargs='?', default=os.environ.get('OFM_MODE', 'start'))
    parser.add_argument('--data-dir', type=Path, default=Path('/home/container'))
    parser.add_argument('--app-dir', type=Path, default=Path('/opt/open-freemode'))
    args = parser.parse_args()
    data, app = args.data_dir.absolute(), args.app_dir.absolute()
    try:
        if args.mode not in ['install', 'configure', 'start', 'migrate']:
            raise ValueError('OFM_MODE must be start or migrate')
        seed(data, app)
        if args.mode == 'install':
            print('Open Freemode persistent directories initialized; existing operator settings preserved.')
            return 0
        environment = configure(data, os.environ)
        if args.mode == 'configure':
            print('Private configuration generated.')
            return 0
        migration = subprocess.call(['node', str(app / 'scripts/migrate-legacy.mjs'),
                                     str(data / 'config/database.json')], env=environment)
        if migration or args.mode == 'migrate':
            return migration
        runtime = runtime_root(data, app, environment)
        return supervise(command(runtime) + ['+set', 'onesync', 'on', '+exec', 'server.cfg'],
                         environment, data / 'server-data')
    except (ValueError, OSError) as error:
        # OSError text may include private paths; only our fixed validation messages are shown.
        print(str(error) if isinstance(error, ValueError) else 'Launcher filesystem/process error; check private paths and permissions.', file=sys.stderr)
        return 1


if __name__ == '__main__':
    sys.exit(main())
